import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

export default Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();

        if (!user) return Response.json({ error: "Unauthorized" }, { status: 401 });

        const payload = await req.json().catch(() => ({}));
        
        // Input Parsing & Defaults
        const userId = payload.user_id || user.email;
        const context = payload.context || {};
        const options = payload.options || {};
        
        const k_items = context.k_items || 30;
        const k_categories = context.k_categories || 5;
        const k_stores = context.k_stores || 3;
        
        const user_lat = context.user_lat;
        const user_lon = context.user_lon;
        const current_store_id = context.current_store_id;

        const lookback_days = options.lookback_days || 90;
        const exclude_recent_days = options.exclude_recent_days || 10;
        const cold_start_min_receipts = options.cold_start_min_receipts || 3;

        // Helper: Haversine Distance
        const getDistanceKm = (lat1, lon1, lat2, lon2) => {
            if (!lat1 || !lon1 || !lat2 || !lon2) return Infinity;
            const R = 6371; 
            const dLat = (lat2 - lat1) * Math.PI / 180;
            const dLon = (lon2 - lon1) * Math.PI / 180;
            const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
                      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
                      Math.sin(dLon/2) * Math.sin(dLon/2);
            const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
            return R * c;
        };

        // Feature Flag Check for V2 Strategy
        const rec_strategy_v2_enabled = Deno.env.get("REC_STRATEGY_V2_ENABLED") === "true" || payload.force_v2;

        if (rec_strategy_v2_enabled) {
            // --- V2 STRATEGY START ---
            
            // 1. Get Receipt Count
            // Try to get from UserProfileVector cache first
            const vectors = await base44.entities.UserProfileVector.filter({ user_id: userId });
            let receiptCount = vectors[0]?.receipt_count_cached;
            
            if (receiptCount === undefined) {
                const res = await base44.functions.invoke('calculateUserReceiptCount', { userId });
                receiptCount = res.data?.count || 0;
            }

            const strategy = receiptCount < 20 ? 'COLLAB' : 'HYBRID';
            const algorithm = strategy === 'COLLAB' ? 'cf_v2_cold_start' : 'hybrid_v2_weighted';

            // 2. Invoke Strategy
            const strategyFn = strategy === 'COLLAB' ? 'collaborativeFilteringStrategy' : 'hybridRecommendationStrategy';
            const strategyRes = await base44.functions.invoke(strategyFn, { userId, k_items });
            
            if (!strategyRes.data || strategyRes.data.error) {
                console.error("Strategy failed", strategyRes.data?.error);
                // Fallback to empty or throw? Let's throw to fallback to V1 if wrapped in try/catch? 
                // No, sticking to V2 path logic.
                throw new Error("Strategy generation failed: " + strategyRes.data?.error);
            }

            const rawCandidates = strategyRes.data.candidates || [];
            const meta = strategyRes.data.meta || {};

            // 3. Create Run
            const run = await base44.entities.RecommendationRun.create({
                user_id: userId,
                context_store_chain_id: context.store_chain_id,
                context_region: context.region,
                algorithm: algorithm,
                model_version: 'v2',
                created_at: new Date().toISOString()
            });

            // 4. Persist Candidates
            // Map raw candidates to DB entities
            const dbCandidates = rawCandidates.map((c, idx) => ({
                run_id: run.id,
                candidate_type: c.candidate_type,
                canonical_product_id: c.canonical_product_id,
                score: c.score,
                reason_code: c.reason_code,
                rank: idx + 1
            }));
            
            if (dbCandidates.length > 0) {
                await base44.entities.RecommendationCandidate.bulkCreate(dbCandidates);
            }
            
            // 5. Store Source Meta
            await base44.entities.RecommendationSourceMeta.create({
                recommendation_id: run.id,
                user_id: userId,
                source_type: strategy,
                weights_json: meta.weights || {},
                reason_short: meta.reason || "Recommendation generated by V2 strategy",
                created_at: new Date().toISOString()
            });

            // 6. Enrich for Response (Reuse enrichment logic if possible or replicate)
            // We need to fetch product details to return rich objects
            const productIds = dbCandidates.map(c => c.canonical_product_id);
            const products = [];
            // Batch fetch logic
            // Simple loop for now or improved batch if available
            for (const id of productIds) {
                 const res = await base44.entities.Product.filter({ gtin: id });
                 if (res[0]) products.push(res[0]);
            }
            
            const enrich = (cands) => cands.map(c => {
                const p = products.find(prod => prod.gtin === c.canonical_product_id);
                return {
                    candidate_id: c.canonical_product_id, // Use product ID as ID for simplicity in response
                    canonical_product_id: c.canonical_product_id,
                    score: c.score,
                    reason_code: c.reason_code,
                    name: p?.canonical_name || p?.name || c.canonical_product_id,
                    image_url: p?.image_url,
                    description: p?.description
                };
            });

            const responseCandidates = {
                items: enrich(rawCandidates),
                stores: [], // V2 strategy currently focuses on products in the prompt logic provided. 
                           // If stores needed, we'd need to add store strategy. 
                           // For now returning empty stores to avoid breaking UI.
                categories: []
            };

            return Response.json({
                run: {
                    id: run.id,
                    user_id: userId,
                    algorithm: algorithm,
                    model_version: "v2",
                    created_at: run.created_at,
                    meta: meta
                },
                candidates: responseCandidates
            });
            // --- V2 STRATEGY END ---
        }

        // 1. Determine Algorithm (Cold vs Warm) - V1 Fallback
        // Check receipt count in last 60 days
        const sixtyDaysAgo = new Date();
        sixtyDaysAgo.setDate(sixtyDaysAgo.getDate() - 60);
        
        const recentReceipts = await base44.entities.Receipt.filter({ 
            created_by: userId, 
            purchased_at: { $gte: sixtyDaysAgo.toISOString() } 
        });

        const algorithm = recentReceipts.length < cold_start_min_receipts 
            ? "cf_profile_cold_start" 
            : "cf_behavior_warm_start";

        // 2. Freshness Check (Vectors & Neighbors)
        // Check if recent snapshot exists (e.g. last 24h)
        const oneDayAgo = new Date();
        oneDayAgo.setDate(oneDayAgo.getDate() - 1);
        
        const snapshots = await base44.entities.UserVectorSnapshot.filter({
            user_id: userId,
            computed_at: { $gte: oneDayAgo.toISOString() }
        });

        if (snapshots.length === 0) {
            // Recompute on demand
            await base44.functions.invoke('buildUserVectors', { userId });
            await base44.functions.invoke('computeSimilarUsers', { userId });
        }

        // 3. Get Neighbors
        const edges = await base44.entities.SimilarUserEdge.filter({ 
            user_id: userId
        }, '-similarity', k_items);

        // 4. Aggregate Candidates
        const chainScores = {};
        const catScores = {};
        const prodScores = {};

        if (edges.length === 0) {
            // Cold Start Fallback: Content-Based / Popularity
            // Fetch User Profile for constraints
            const profiles = await base44.entities.UserProfile.filter({ created_by: userId });
            const userProfile = profiles[0];

            // Fetch a batch of products to score based on profile
            const fallbackProducts = await base44.entities.Product.list({ limit: 100 });
            
            fallbackProducts.forEach(p => {
                let score = 0.1; // Low base score
                
                // Boost based on profile
                if (userProfile) {
                    if (userProfile.diet === 'vegan' && p.is_vegan) score += 0.5;
                    if (userProfile.diet === 'vegetarian' && (p.is_vegan || p.is_vegetarian)) score += 0.3;
                    if (userProfile.diet === 'gluten_free' && p.is_gluten_free) score += 0.5;
                    if (userProfile.kosher_level && userProfile.kosher_level !== 'none' && p.is_kosher) score += 0.5;
                    
                    // Boost based on budget focus? Maybe cheaper items? We don't have price here easily without join.
                }
                
                prodScores[p.gtin] = score;
                
                if (p.category) {
                    catScores[p.category] = (catScores[p.category] || 0) + (score * 0.2);
                }
            });
        }

        // Fetch exclude list (my recent purchases)
        const excludeDate = new Date();
        excludeDate.setDate(excludeDate.getDate() - exclude_recent_days);
        
        // Fetch my recent receipt items to exclude
        // This query might be heavy if many receipts. 
        // Optimization: rely on behavior vector which encodes recent purchases? 
        // Or just fetch recent receipts headers then items.
        // For prototype, we'll skip detailed exclusion or do a simple fetch.
        const myRecentReceipts = await base44.entities.Receipt.filter({
            created_by: userId,
            purchased_at: { $gte: excludeDate.toISOString() }
        });
        const myRecentReceiptIds = myRecentReceipts.map(r => r.id);
        // We need items. Fetch items for these receipts? 
        // If Receipt has 'items' json field (from schema), we use that.
        // Schema says Receipt has 'items' array.
        const excludeProductIds = new Set();
        myRecentReceipts.forEach(r => {
            if (r.items) {
                r.items.forEach(i => {
                    if (i.product_id) excludeProductIds.add(i.product_id); // Assuming product_id is canonical
                    if (i.code) excludeProductIds.add(i.code); // Fallback
                });
            }
        });

        // Fetch Neighbors' Vectors to aggregate
        // Logic copied from generateCollaborativeRecommendations but adapted
        // We need behavior vectors of neighbors.
        const topNeighbors = edges.slice(0, 10); // Limit to 10 for performance
        
        const neighborVectors = await Promise.all(topNeighbors.map(async (edge) => {
            const snaps = await base44.entities.UserVectorSnapshot.filter({ 
                user_id: edge.neighbor_user_id, 
                vector_type: 'behavior' 
            }, '-computed_at', 1);
            return {
                user_id: edge.neighbor_user_id,
                similarity: edge.similarity,
                vector: snaps[0]?.vector_json || {}
            };
        }));

        neighborVectors.forEach(n => {
            const vec = n.vector;
            const sim = n.similarity;
            
            for (const key in vec) {
                const val = vec[key];
                if (key.startsWith('chain_')) {
                    const id = key.replace('chain_', '');
                    chainScores[id] = (chainScores[id] || 0) + (val * sim);
                } else if (key.startsWith('cat_')) {
                    const id = key.replace('cat_', '');
                    catScores[id] = (catScores[id] || 0) + (val * sim);
                } else if (key.startsWith('prod_')) {
                    const id = key.replace('prod_', '');
                    if (!excludeProductIds.has(id)) {
                        prodScores[id] = (prodScores[id] || 0) + (val * sim);
                    }
                }
            }
        });

        // --- CONTEXT AUGMENTATION ---
        
        // A. Location Boost (Stores)
        if (user_lat && user_lon) {
            // Fetch all stores (or cache? list() is fine for now)
            // Ideally we query stores near bbox, but list() is okay for proto.
            const allStores = await base44.entities.Store.list();
            const chainMinDist = {};

            allStores.forEach(s => {
                const d = getDistanceKm(user_lat, user_lon, s.latitude, s.longitude);
                if (d < 50) { // Only consider stores within 50km
                    if (!chainMinDist[s.chain_id] || d < chainMinDist[s.chain_id]) {
                        chainMinDist[s.chain_id] = d;
                    }
                }
            });

            // Boost logic: Closer = Higher boost
            // 0km = 1.0 boost, 10km = 0.5 boost, 50km = 0 boost
            Object.entries(chainMinDist).forEach(([chainId, dist]) => {
                const boost = Math.max(0, 1 - (dist / 20)); // Linear decay up to 20km
                if (boost > 0) {
                    chainScores[chainId] = (chainScores[chainId] || 0) + boost;
                }
            });
        }

        // B. Promotion/Inventory Boost (Products)
        // Fetch active promotions
        const now = new Date().toISOString();
        const activePromos = await base44.entities.Promotion.filter({
            starts_at: { $lte: now },
            ends_at: { $gte: now }
        });
        
        // If current_store_id provided, fetch its specific pricing/inventory
        let storePrices = [];
        if (current_store_id) {
            storePrices = await base44.entities.ProductPrice.filter({ store_id: current_store_id });
        }

        // Apply Boosts
        // 1. Global Promo Boost (if no specific store or generic chain promos)
        // Map promos to products? Promos usually linked to products?
        // Schema: Promotion has chain_id, store_id. It describes discount. 
        // It doesn't strictly link to GTIN in the schema provided (Relation? No, just name/desc). 
        // Assuming "name" or description matches or we need a join table.
        // Wait, schema check: Promotion -> properties: name, description... no product_id?
        // Ah, typically promos are complex. Let's assume for this proto we don't link promos to GTINs easily 
        // without a separate lookup or if `ProductPrice` has `is_promoted` flag?
        // `ProductPrice` schema has `allow_discount`. 
        // Let's rely on `storePrices` if available.
        
        if (current_store_id && storePrices.length > 0) {
            storePrices.forEach(p => {
                if (p.availability_status === 'out_of_stock') {
                    // Penalize heavily
                    if (prodScores[p.gtin]) prodScores[p.gtin] *= 0.1;
                } else {
                     // Boost if price is good? Or just boost availability?
                     // Let's slight boost available items in current store
                     prodScores[p.gtin] = (prodScores[p.gtin] || 0) + 0.2;
                }
            });
        }

        // 5. Create Run & Candidates
        const run = await base44.entities.RecommendationRun.create({
            user_id: userId,
            context_store_chain_id: context.store_chain_id,
            context_region: context.region,
            algorithm: algorithm,
            model_version: 'cf_v1',
            created_at: new Date().toISOString()
        });

        // Helper to get top keys
        const getTopKeys = (scores, limit) => Object.entries(scores)
            .sort(([, a], [, b]) => b - a)
            .slice(0, limit)
            .map(([id, score]) => ({ id, score }));

        const topChainKeys = getTopKeys(chainScores, k_stores);
        const topCatKeys = getTopKeys(catScores, k_categories);
        const topProdKeys = getTopKeys(prodScores, k_items);

        // Validate Chains
        const validatedChains = [];
        await Promise.all(topChainKeys.map(async ({ id, score }) => {
            const res = await base44.entities.Chain.filter({ id });
            if (res.length > 0) {
                validatedChains.push({ ...res[0], score }); // Keep entity data + score
            }
        }));

        // Validate Products
        const validatedProducts = [];
        await Promise.all(topProdKeys.map(async ({ id, score }) => {
            const res = await base44.entities.Product.filter({ gtin: id }); // Assuming vector uses GTIN/Canonical ID
            if (res.length > 0) {
                validatedProducts.push({ ...res[0], score });
            }
        }));

        // Categories (No DB entity usually, but pass through)
        const validatedCategories = topCatKeys.map(k => ({ category: k.id, score: k.score }));

        // Prepare Candidates for DB
        const dbCandidates = [];
        
        validatedChains.forEach((c, idx) => {
            dbCandidates.push({
                run_id: run.id,
                candidate_type: 'store_chain',
                store_chain_id: c.id,
                score: c.score,
                reason_code: 'collaborative_filtering',
                rank: idx + 1
            });
        });

        validatedCategories.forEach((c, idx) => {
            dbCandidates.push({
                run_id: run.id,
                candidate_type: 'category',
                category: c.category,
                score: c.score,
                reason_code: 'collaborative_filtering',
                rank: idx + 1
            });
        });

        validatedProducts.forEach((p, idx) => {
            dbCandidates.push({
                run_id: run.id,
                candidate_type: 'canonical_product',
                canonical_product_id: p.gtin,
                score: p.score,
                reason_code: 'collaborative_filtering',
                rank: idx + 1
            });
        });

        // Persist
        const createdCandidates = await Promise.all(dbCandidates.map(c => base44.entities.RecommendationCandidate.create(c)));

        // Enrich Response
        const enrich = (candidates, entities, typeField, entityIdField) => {
            return candidates.map(c => {
                const entity = entities.find(e => e[entityIdField] === c[typeField]);
                return {
                    candidate_id: c.id,
                    [typeField]: c[typeField],
                    score: c.score,
                    reason_code: c.reason_code,
                    // Enrich
                    name: entity?.name || entity?.canonical_name || c[typeField],
                    image_url: entity?.logo_url || entity?.image_url,
                    description: entity?.description
                };
            });
        };

        const responseCandidates = {
            stores: enrich(createdCandidates.filter(c => c.candidate_type === 'store_chain'), validatedChains, 'store_chain_id', 'id'),
            categories: createdCandidates.filter(c => c.candidate_type === 'category').map(c => ({ 
                candidate_id: c.id, 
                category: c.category, 
                score: c.score, 
                reason_code: c.reason_code,
                name: c.category // Categories are just strings usually
            })),
            items: enrich(createdCandidates.filter(c => c.candidate_type === 'canonical_product'), validatedProducts, 'canonical_product_id', 'gtin')
        };

        return Response.json({
            run: {
                id: run.id,
                user_id: userId,
                algorithm: algorithm,
                model_version: "cf_v1",
                created_at: run.created_at
            },
            candidates: responseCandidates
        });

    } catch (error) {
        return Response.json({ error: error.message }, { status: 500 });
    }
});